# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2354f87c99c9edf4a3b3abb6ad6eebab2ed5e04eb7be450683e34a38b99c0b56106bb166686f36574fe9052329eedab48f5fcefd63fc75db6ec3533a66cbcc

test:
  secret_key_base: db59d17a87170a0ecb26ed2f0f03150776f06fbff0fcea19bbcb831d86332109e185e12a4b4f018cfa7704d381871b7aae042eb02d119cfd347e4ff3c62d2525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
